name: Katabump Auto Renew
on:
  schedule:
    - cron: '0 12 */3 * *'
  workflow_dispatch:

jobs:
  renew-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: دریافت کدها
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: نصب ابزارها و مرورگر
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium
          playwright install-deps

      - name: اجرای اسکریپت تمدید
        env:
          KATABUMP_EMAIL: ${{ secrets.KATABUMP_EMAIL }}
          KATABUMP_PASSWORD: ${{ secrets.KATABUMP_PASSWORD }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
        run: python renew.py

      - name: فعال نگه داشتن خودکار
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --allow-empty -m "keepalive" || exit 0
          git push || exit 0
